version: '3.9'
services:
  bento:
    image: lewisdoesstuff/bento
    volumes:
      - /home/alafia/Desktop/alafia-apps/bento/config.js:/usr/share/nginx/html/config.js
    ports:
      - 1000:80
    networks:
      - caddy
    labels:
      caddy: home.alafia
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

networks:
  caddy:
    external: true
