version: '3.7'
services:
  ohif:
    image: ohif/app:latest
    networks:
      - caddy
    labels:
      caddy: ohif.alafia
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

networks:
  caddy:
    external: true
